export let networks = {"rs2ModeArtistTermAuthorByPublicationreOFermento.xml_1": {
  "format_version" : "1.0",
  "generated_by" : "cytoscape-3.9.1",
  "target_cytoscapejs_version" : "~2.1",
  "data" : {
    "shared_name" : "rs2ModeArtistTermAuthorByPublicationreOFermento.xml_1",
    "name" : "rs2ModeArtistTermAuthorByPublicationreOFermento.xml_1",
    "SUID" : 1828639,
    "__Annotations" : [ ],
    "selected" : true
  },
  "elements" : {
    "nodes" : [ {
      "data" : {
        "id" : "1828838",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 2,
        "shared_name" : "Filippi, Frederico (1983-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828838,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.5,
        "selected" : false,
        "ClosenessCentrality" : 0.6666666666666666,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Carlos",
        "Radiality" : 0.75,
        "birthDate" : 1983,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Filippi, Frederico (1983-)",
        "personId" : "arFredericoFilippi",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 2.0
      },
      "position" : {
        "x" : 633.9123136418799,
        "y" : -476.2965295371805
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828835",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Mello Landini, Janaina (1974-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Brasil",
        "SUID" : 1828835,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Gotardo",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1974,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Mello Landini, Janaina (1974-)",
        "personId" : "arJanainaLandini",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 206.32413060746546,
        "y" : -183.68497709294286
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828832",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Redondo, Laércio (1967-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828832,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Paranavaí",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1967,
        "Stress" : 0,
        "birthRegion" : "PR",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Redondo, Laércio (1967-)",
        "personId" : "arLaercioRedondo",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -542.3229595718859,
        "y" : 693.4976508215223
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828829",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Rego Macedo, Ronaldo do (1950-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828829,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1950,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Rego Macedo, Ronaldo do (1950-)",
        "personId" : "arRonaldoMacedo",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 206.32413060746546,
        "y" : -396.3197212640124
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828826",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 2,
        "shared_name" : "Guimaraens, Luiz Alphonsus de (1948-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828826,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.5,
        "selected" : false,
        "ClosenessCentrality" : 0.6666666666666666,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belo Horizonte",
        "Radiality" : 0.75,
        "birthDate" : 1948,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Guimaraens, Luiz Alphonsus de (1948-)",
        "personId" : "arLuizGuimaraens",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 2.0
      },
      "position" : {
        "x" : 689.9123136418799,
        "y" : -658.2965295371805
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828823",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Paulino, Rosana (1967-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828823,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Paulo",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1967,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Paulino, Rosana (1967-)",
        "personId" : "arRosanaPaulino",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -419.5582327856516,
        "y" : 939.0271043939906
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828820",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Garcia, Zé Carlos (1973-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828820,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Aracaju",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1973,
        "Stress" : 0,
        "birthRegion" : "SE",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Garcia, Zé Carlos (1973-)",
        "personId" : "arZeGarcia",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 463.8938834709526,
        "y" : -105.85525899912636
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828817",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Zerbini, Luiz (1959-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828817,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Paulo",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1959,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Zerbini, Luiz (1959-)",
        "personId" : "arLuizZerbini",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -223.35241314435444,
        "y" : -290.00234917847786
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828814",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Akerman, Chantal (1950-2015)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Bélgica",
        "SUID" : 1828814,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Bruxelas",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1950,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Akerman, Chantal (1950-2015)",
        "personId" : "arChantalAkerman",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -665.0876863581201,
        "y" : 693.4976508215225
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828811",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Sant’Ana, Tiago (1990-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Brasil",
        "SUID" : 1828811,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Santo Antônio de Jesus",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1990,
        "Stress" : 0,
        "birthRegion" : "BA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Sant’Ana, Tiago (1990-)",
        "personId" : "arTiagoSantAna",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -39.20532296500289,
        "y" : -608.954465435082
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828808",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Bulcão, Athos (1918-2008)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828808,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1918,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Bulcão, Athos (1918-2008)",
        "personId" : "arAthosBulcao",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 22.177040428114083,
        "y" : -77.36760500740809
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828805",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Silva Costa, Amélia (1976-1922)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828805,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1976,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Silva Costa, Amélia (1976-1922)",
        "personId" : "arAmeliaCosta",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -593.1737743877718,
        "y" : 519.8821092194023
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828802",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Faro, Magdalena del",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "NA",
        "SUID" : 1828802,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9256661991584852,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Faro, Magdalena del",
        "personId" : "arMagdalenaFaro",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -419.5582327856519,
        "y" : 447.9681972490539
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828799",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Nepomuceno, Maria (1976-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Brasil",
        "SUID" : 1828799,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1976,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Nepomuceno, Maria (1976-)",
        "personId" : "arMariaNepomuceno",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -245.94269118353196,
        "y" : 519.8821092194019
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828796",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Martins, Maria (1894-1973)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828796,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Campanha",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1894,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Martins, Maria (1894-1973)",
        "personId" : "arMariaMartins",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -174.02877921318316,
        "y" : 693.4976508215223
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828793",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Salgado, Cristina (1957-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828793,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1957,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Salgado, Cristina (1957-)",
        "personId" : "arCristinaSalgado",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -245.94269118353162,
        "y" : 867.1131924236424
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828790",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Bourgeois, Louise Joséphine (1911-2010)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "França",
        "SUID" : 1828790,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Paris",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1911,
        "Stress" : 0,
        "birthRegion" : "Île de France",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Bourgeois, Louise Joséphine (1911-2010)",
        "personId" : "arLouiseBourgeois",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -358.17586939253454,
        "y" : 799.815022907057
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828787",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Sá, Neide Dias de (1940-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828787,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1940,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Sá, Neide Dias de (1940-)",
        "personId" : "arNeideSa",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -480.94059617876877,
        "y" : 799.815022907057
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828784",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Schendel, Mira (1919-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Suíça",
        "SUID" : 1828784,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Zurique",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1919,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Schendel, Mira (1919-1988)",
        "personId" : "arMiraSchendel",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -480.9405961787689,
        "y" : 587.1802787359875
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828781",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Milhazes, Beatriz (1960-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828781,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1960,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Milhazes, Beatriz (1960-)",
        "personId" : "arBeatrizMilhazes",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -358.17586939253454,
        "y" : 587.1802787359875
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828778",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Baltar, Brígida (1959-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828778,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1959,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Baltar, Brígida (1959-)",
        "personId" : "arBrigidaBaltar",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -296.79350599941745,
        "y" : 693.4976508215223
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828775",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Houayek, Hugo (1979-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828775,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1979,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Houayek, Hugo (1979-)",
        "personId" : "arHugoHouayek",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -593.1737743877716,
        "y" : 867.1131924236424
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828772",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Basquiat, Jean-Michel (1960-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Estados Unidos",
        "SUID" : 1828772,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Nova Iorque",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1960,
        "Stress" : 0,
        "birthRegion" : "Nova Iorque",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Basquiat, Jean-Michel (1960-1988)",
        "personId" : "arJeanMichelBasquiat",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 144.94176721434826,
        "y" : -658.2965295371805
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828769",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Rocha Pitta, Matheus (1980-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828769,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São João del Rei",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1980,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Rocha Pitta, Matheus (1980-)",
        "personId" : "arMatheusPitta",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 463.89388347095235,
        "y" : -474.14943935782946
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828766",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Freitas, Ana",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828766,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9481065918653576,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Freitas, Ana",
        "personId" : "arAnaFreitas",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 329.08885739369964,
        "y" : 28.949767078126683
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828763",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Lima Dias, Antônio Manuel (1944-2018)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828763,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Campina Grande",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1944,
        "Stress" : 0,
        "birthRegion" : "PB",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Lima Dias, Antônio Manuel (1944-2018)",
        "personId" : "arAntonioDias",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -67.69297695672128,
        "y" : -167.23762239224345
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828760",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Braga, Rodrigo (1976-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828760,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Manaus",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1976,
        "Stress" : 0,
        "birthRegion" : "AM",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Braga, Rodrigo (1976-)",
        "personId" : "arRodrigoBraga",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -67.69297695672128,
        "y" : -412.76707596471203
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828757",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Mello Mourão, Antonio José de (1952-2016)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828757,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Palmares",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1952,
        "Stress" : 0,
        "birthRegion" : "PE",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Mello Mourão, Antonio José de (1952-2016)",
        "personId" : "arAtonioMourao",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 144.94176721434837,
        "y" : 78.29183118022502
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828754",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Freitas, Iole de (1945-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828754,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belo Horizonte",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1945,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Freitas, Iole de (1945-)",
        "personId" : "arIoleFreitas",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 144.94176721434826,
        "y" : -535.5318027509462
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828751",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Fernández, Magdalena (1964-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Venezuela",
        "SUID" : 1828751,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1964,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Fernández, Magdalena (1964-)",
        "personId" : "arMagdalenaFernandez",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 357.5765113854176,
        "y" : -412.76707596471226
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828748",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Vardenega, Gregorio (1923-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Itália",
        "SUID" : 1828748,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1923,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Vardenega, Gregorio (1923-)",
        "personId" : "arGregorioVardenega",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 357.5765113854178,
        "y" : -167.23762239224345
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828745",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Parc, Julio Le (1928-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Argentina",
        "SUID" : 1828745,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Mendoza",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1928,
        "Stress" : 0,
        "birthRegion" : "Mendoza",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Parc, Julio Le (1928-)",
        "personId" : "arJulioParc",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 144.94176721434826,
        "y" : -44.472895606009274
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828742",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Castro, Willys de (1926-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828742,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Uberlândia",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1926,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Castro, Willys de (1926-1988)",
        "personId" : "arWillysCastro",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 83.55940382123117,
        "y" : -183.68497709294286
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828739",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Serpa, Ivan (1923-1973)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828739,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1923,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Serpa, Ivan (1923-1973)",
        "personId" : "arIvanSerpa",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 22.177040428114083,
        "y" : -290.00234917847763
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828736",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Volpi, Alfredo (1896-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Itália",
        "SUID" : 1828736,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Lucca",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1896,
        "Stress" : 0,
        "birthRegion" : "Toscana",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Volpi, Alfredo (1896-1988)",
        "personId" : "arAlfredoVolpi",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 83.55940382123106,
        "y" : -396.3197212640124
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828733",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Cordeiro, Waldemar (1925-1973)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Itália",
        "SUID" : 1828733,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Roma",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1925,
        "Stress" : 0,
        "birthRegion" : "Lácio",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Cordeiro, Waldemar (1925-1973)",
        "personId" : "arWaldemarCordeiro",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 267.70649400058244,
        "y" : -290.00234917847763
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828730",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 2,
        "shared_name" : "Maiolino, Anna Maria (1942-)",
        "TopologicalCoefficient" : 0.5,
        "idnoEIC" : "EIC",
        "birthCountry" : "Itália",
        "SUID" : 1828730,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.9565217391304348,
        "selected" : false,
        "ClosenessCentrality" : 0.5111111111111111,
        "Degree" : 2,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Scalea",
        "Radiality" : 0.9691444600280505,
        "birthDate" : 1942,
        "Stress" : 930,
        "birthRegion" : "Calábria",
        "BetweennessCentrality" : 0.4492753623188406,
        "NumberOfUndirectedEdges" : 2,
        "name" : "Maiolino, Anna Maria (1942-)",
        "personId" : "arAnnaMaiolino",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 23.0
      },
      "position" : {
        "x" : -185.55823278565174,
        "y" : 288.49765082152226
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828727",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Pape, Lygia (1927-2004)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828727,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Nova Friburgo",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1927,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Pape, Lygia (1927-2004)",
        "personId" : "arLygiaPape",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -39.205322965003006,
        "y" : 28.949767078126683
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828724",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Espírito Santo, Iran do (1963-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828724,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Mococa",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1963,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Espírito Santo, Iran do (1963-)",
        "personId" : "arIranSanto",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -174.01034904225617,
        "y" : -105.85525899912636
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828721",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Pérez Monzón, Gustavo (1956-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Cuba",
        "SUID" : 1828721,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1956,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Pérez Monzón, Gustavo (1956-)",
        "personId" : "arGustavoMonzon",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -174.01034904225605,
        "y" : -474.14943935782924
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828718",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Mello, Vicente de (1967-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828718,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Paulo",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1967,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Mello, Vicente de (1967-)",
        "personId" : "arVicenteMello",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -100.58768635812021,
        "y" : -290.00234917847774
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828715",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Machado, Ivens (1942-2015)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828715,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Florianópolis",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1942,
        "Stress" : 0,
        "birthRegion" : "SC",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Machado, Ivens (1942-2015)",
        "personId" : "arIvensMachado",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 22.177040428114083,
        "y" : -502.6370933495474
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828712",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Heráclito, Ayrson (1969-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828712,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Macaúbas",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1969,
        "Stress" : 0,
        "birthRegion" : "BA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Heráclito, Ayrson (1969-)",
        "personId" : "arAyrsonHeraclito",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 267.7064940005823,
        "y" : -502.6370933495474
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828709",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Magno, Luciana (1987-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828709,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belém",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1987,
        "Stress" : 0,
        "birthRegion" : "PA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Magno, Luciana (1987-)",
        "personId" : "arLucianaMagno",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 390.4712207868166,
        "y" : -290.00234917847763
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828706",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Reale, Berna (1965-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828706,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belém",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1965,
        "Stress" : 0,
        "birthRegion" : "PA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Reale, Berna (1965-)",
        "personId" : "arBernaReale",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 267.70649400058244,
        "y" : -77.36760500740809
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828703",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Clark, Lygia (1920-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828703,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belo Horizonte",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1920,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Clark, Lygia (1920-1988)",
        "personId" : "arLygiaClark",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 329.0888573936994,
        "y" : -608.954465435082
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828700",
        "idnoWKD" : "WKD",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 4,
        "shared_name" : "Oiticica, Hélio (1937-1980)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 1828700,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 2,
        "PartnerOfMultiEdgedNodePairs" : 1,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1937,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 2,
        "name" : "Oiticica, Hélio (1937-1980)",
        "personId" : "arHelioOiticica",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 513.235947573051,
        "y" : -290.00234917847763
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828697",
        "idnoWKD" : "NA",
        "occupation" : "OUTRO",
        "Eccentricity" : 1,
        "shared_name" : "Lattavo, Patricia (1968-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Brasil",
        "SUID" : 1828697,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.0,
        "selected" : false,
        "ClosenessCentrality" : 1.0,
        "Degree" : 2,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 1.0,
        "birthDate" : 1968,
        "Stress" : 2,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 1.0,
        "NumberOfUndirectedEdges" : 2,
        "name" : "Lattavo, Patricia (1968-)",
        "personId" : "auPatriciaLattavo",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 1.0
      },
      "position" : {
        "x" : 661.9123136418799,
        "y" : -566.2965295371805
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828694",
        "idnoWKD" : "NA",
        "occupation" : "OUTRO",
        "Eccentricity" : 3,
        "shared_name" : "Fonseca, Ludmilla",
        "TopologicalCoefficient" : 0.06666666666666667,
        "idnoEIC" : "NA",
        "birthCountry" : "Brasil",
        "SUID" : 1828694,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.3260869565217392,
        "selected" : false,
        "ClosenessCentrality" : 0.42990654205607476,
        "Degree" : 15,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9572230014025246,
        "Stress" : 1078,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.5207729468599034,
        "NumberOfUndirectedEdges" : 15,
        "name" : "Fonseca, Ludmilla",
        "personId" : "auLudmillaFonseca",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 1.0666666666666667
      },
      "position" : {
        "x" : -419.5582327856517,
        "y" : 693.4976508215223
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828667",
        "idnoWKD" : "NA",
        "occupation" : "ARTISTA VISUAL",
        "Eccentricity" : 3,
        "shared_name" : "Veiga, Valesca (1972-)",
        "TopologicalCoefficient" : 0.03225806451612903,
        "idnoEIC" : "NA",
        "birthCountry" : "NA",
        "SUID" : 1828667,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.6304347826086956,
        "selected" : false,
        "ClosenessCentrality" : 0.6133333333333334,
        "Degree" : 32,
        "PartnerOfMultiEdgedNodePairs" : 1,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.979663394109397,
        "birthDate" : 1972,
        "Stress" : 1830,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.8840579710144927,
        "NumberOfUndirectedEdges" : 32,
        "name" : "Veiga, Valesca (1972-)",
        "personId" : "auValescaVeiga",
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 1.032258064516129
      },
      "position" : {
        "x" : 144.94176721434826,
        "y" : -290.00234917847763
      },
      "selected" : false
    } ],
    "edges" : [ {
      "data" : {
        "id" : "1828935",
        "source" : "1828697",
        "target" : "1828838",
        "EdgeBetweenness" : 4.0,
        "shared_name" : "auPatriciaLattavo (-) arFredericoFilippi",
        "shared_interaction" : "-",
        "name" : "auPatriciaLattavo (-) arFredericoFilippi",
        "interaction" : "-",
        "SUID" : 1828935,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828929",
        "source" : "1828697",
        "target" : "1828826",
        "EdgeBetweenness" : 4.0,
        "shared_name" : "auPatriciaLattavo (-) arLuizGuimaraens",
        "shared_interaction" : "-",
        "name" : "auPatriciaLattavo (-) arLuizGuimaraens",
        "interaction" : "-",
        "SUID" : 1828929,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828933",
        "source" : "1828694",
        "target" : "1828832",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arLaercioRedondo",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arLaercioRedondo",
        "interaction" : "-",
        "SUID" : 1828933,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828927",
        "source" : "1828694",
        "target" : "1828823",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arRosanaPaulino",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arRosanaPaulino",
        "interaction" : "-",
        "SUID" : 1828927,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828921",
        "source" : "1828694",
        "target" : "1828814",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arChantalAkerman",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arChantalAkerman",
        "interaction" : "-",
        "SUID" : 1828921,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828915",
        "source" : "1828694",
        "target" : "1828805",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arAmeliaCosta",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arAmeliaCosta",
        "interaction" : "-",
        "SUID" : 1828915,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828913",
        "source" : "1828694",
        "target" : "1828802",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arMagdalenaFaro",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arMagdalenaFaro",
        "interaction" : "-",
        "SUID" : 1828913,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828911",
        "source" : "1828694",
        "target" : "1828799",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arMariaNepomuceno",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arMariaNepomuceno",
        "interaction" : "-",
        "SUID" : 1828911,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828909",
        "source" : "1828694",
        "target" : "1828796",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arMariaMartins",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arMariaMartins",
        "interaction" : "-",
        "SUID" : 1828909,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828907",
        "source" : "1828694",
        "target" : "1828793",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arCristinaSalgado",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arCristinaSalgado",
        "interaction" : "-",
        "SUID" : 1828907,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828905",
        "source" : "1828694",
        "target" : "1828790",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arLouiseBourgeois",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arLouiseBourgeois",
        "interaction" : "-",
        "SUID" : 1828905,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828903",
        "source" : "1828694",
        "target" : "1828787",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arNeideSa",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arNeideSa",
        "interaction" : "-",
        "SUID" : 1828903,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828901",
        "source" : "1828694",
        "target" : "1828784",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arMiraSchendel",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arMiraSchendel",
        "interaction" : "-",
        "SUID" : 1828901,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828899",
        "source" : "1828694",
        "target" : "1828781",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arBeatrizMilhazes",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arBeatrizMilhazes",
        "interaction" : "-",
        "SUID" : 1828899,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828897",
        "source" : "1828694",
        "target" : "1828778",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arBrigidaBaltar",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arBrigidaBaltar",
        "interaction" : "-",
        "SUID" : 1828897,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828895",
        "source" : "1828694",
        "target" : "1828730",
        "EdgeBetweenness" : 960.0,
        "shared_name" : "auLudmillaFonseca (-) arAnnaMaiolino",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arAnnaMaiolino",
        "interaction" : "-",
        "SUID" : 1828895,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828893",
        "source" : "1828694",
        "target" : "1828775",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arHugoHouayek",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arHugoHouayek",
        "interaction" : "-",
        "SUID" : 1828893,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828937",
        "source" : "1828667",
        "target" : "1828835",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arJanainaLandini",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arJanainaLandini",
        "interaction" : "-",
        "SUID" : 1828937,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828931",
        "source" : "1828667",
        "target" : "1828829",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arRonaldoMacedo",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arRonaldoMacedo",
        "interaction" : "-",
        "SUID" : 1828931,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828925",
        "source" : "1828667",
        "target" : "1828817",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arLuizZerbini",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arLuizZerbini",
        "interaction" : "-",
        "SUID" : 1828925,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828923",
        "source" : "1828667",
        "target" : "1828811",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arTiagoSantAna",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arTiagoSantAna",
        "interaction" : "-",
        "SUID" : 1828923,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828919",
        "source" : "1828667",
        "target" : "1828820",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arZeGarcia",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arZeGarcia",
        "interaction" : "-",
        "SUID" : 1828919,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828917",
        "source" : "1828667",
        "target" : "1828808",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAthosBulcao",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAthosBulcao",
        "interaction" : "-",
        "SUID" : 1828917,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828891",
        "source" : "1828667",
        "target" : "1828772",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arJeanMichelBasquiat",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arJeanMichelBasquiat",
        "interaction" : "-",
        "SUID" : 1828891,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828889",
        "source" : "1828667",
        "target" : "1828769",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arMatheusPitta",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arMatheusPitta",
        "interaction" : "-",
        "SUID" : 1828889,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828887",
        "source" : "1828667",
        "target" : "1828766",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAnaFreitas",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAnaFreitas",
        "interaction" : "-",
        "SUID" : 1828887,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828885",
        "source" : "1828667",
        "target" : "1828763",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAntonioDias",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAntonioDias",
        "interaction" : "-",
        "SUID" : 1828885,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828883",
        "source" : "1828667",
        "target" : "1828760",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arRodrigoBraga",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arRodrigoBraga",
        "interaction" : "-",
        "SUID" : 1828883,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828881",
        "source" : "1828667",
        "target" : "1828754",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arIoleFreitas",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arIoleFreitas",
        "interaction" : "-",
        "SUID" : 1828881,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828879",
        "source" : "1828667",
        "target" : "1828751",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arMagdalenaFernandez",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arMagdalenaFernandez",
        "interaction" : "-",
        "SUID" : 1828879,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828877",
        "source" : "1828667",
        "target" : "1828748",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arGregorioVardenega",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arGregorioVardenega",
        "interaction" : "-",
        "SUID" : 1828877,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828875",
        "source" : "1828667",
        "target" : "1828745",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arJulioParc",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arJulioParc",
        "interaction" : "-",
        "SUID" : 1828875,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828873",
        "source" : "1828667",
        "target" : "1828742",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arWillysCastro",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arWillysCastro",
        "interaction" : "-",
        "SUID" : 1828873,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828871",
        "source" : "1828667",
        "target" : "1828739",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arIvanSerpa",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arIvanSerpa",
        "interaction" : "-",
        "SUID" : 1828871,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828869",
        "source" : "1828667",
        "target" : "1828736",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAlfredoVolpi",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAlfredoVolpi",
        "interaction" : "-",
        "SUID" : 1828869,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828867",
        "source" : "1828667",
        "target" : "1828733",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arWaldemarCordeiro",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arWaldemarCordeiro",
        "interaction" : "-",
        "SUID" : 1828867,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828865",
        "source" : "1828667",
        "target" : "1828730",
        "EdgeBetweenness" : 992.0,
        "shared_name" : "auValescaVeiga (-) arAnnaMaiolino",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAnnaMaiolino",
        "interaction" : "-",
        "SUID" : 1828865,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828863",
        "source" : "1828667",
        "target" : "1828727",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arLygiaPape",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arLygiaPape",
        "interaction" : "-",
        "SUID" : 1828863,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828861",
        "source" : "1828667",
        "target" : "1828724",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arIranSanto",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arIranSanto",
        "interaction" : "-",
        "SUID" : 1828861,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828859",
        "source" : "1828667",
        "target" : "1828721",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arGustavoMonzon",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arGustavoMonzon",
        "interaction" : "-",
        "SUID" : 1828859,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828857",
        "source" : "1828667",
        "target" : "1828703",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arLygiaClark",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arLygiaClark",
        "interaction" : "-",
        "SUID" : 1828857,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828855",
        "source" : "1828667",
        "target" : "1828700",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arHelioOiticica",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arHelioOiticica",
        "interaction" : "-",
        "SUID" : 1828855,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 2
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828853",
        "source" : "1828667",
        "target" : "1828757",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAtonioMourao",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAtonioMourao",
        "interaction" : "-",
        "SUID" : 1828853,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828851",
        "source" : "1828667",
        "target" : "1828718",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arVicenteMello",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arVicenteMello",
        "interaction" : "-",
        "SUID" : 1828851,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828849",
        "source" : "1828667",
        "target" : "1828715",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arIvensMachado",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arIvensMachado",
        "interaction" : "-",
        "SUID" : 1828849,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828847",
        "source" : "1828667",
        "target" : "1828712",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAyrsonHeraclito",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAyrsonHeraclito",
        "interaction" : "-",
        "SUID" : 1828847,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828845",
        "source" : "1828667",
        "target" : "1828709",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arLucianaMagno",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arLucianaMagno",
        "interaction" : "-",
        "SUID" : 1828845,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "1828843",
        "source" : "1828667",
        "target" : "1828706",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arBernaReale",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arBernaReale",
        "interaction" : "-",
        "SUID" : 1828843,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    } ]
  }
}}