export let networks = {"rs2ModeArtistTermAuthorByPublicationreOFermento.xml_1": {
  "format_version" : "1.0",
  "generated_by" : "cytoscape-3.9.1",
  "target_cytoscapejs_version" : "~2.1",
  "data" : {
    "shared_name" : "rs2ModeArtistTermAuthorByPublicationreOFermento.xml_1",
    "name" : "rs2ModeArtistTermAuthorByPublicationreOFermento.xml_1",
    "SUID" : 2689996,
    "__Annotations" : [ ],
    "selected" : true
  },
  "elements" : {
    "nodes" : [ {
      "data" : {
        "id" : "2690198",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 2,
        "shared_name" : "Filippi, Frederico (1983-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690198,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.5,
        "selected" : false,
        "ClosenessCentrality" : 0.6666666666666666,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Carlos",
        "Radiality" : 0.75,
        "birthDate" : 1983,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Filippi, Frederico (1983-)",
        "personId" : "arFredericoFilippi",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 2.0
      },
      "position" : {
        "x" : 498.26712759256793,
        "y" : -421.24942613696277
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690195",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Mello Landini, Janaina (1974-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690195,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Gotardo",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1974,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Mello Landini, Janaina (1974-)",
        "personId" : "arJanainaLandini",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 385.20976773928265,
        "y" : -185.1527021856664
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690192",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Redondo, Laércio (1967-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690192,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Paranavaí",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1967,
        "Stress" : 0,
        "birthRegion" : "PR",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Redondo, Laércio (1967-)",
        "personId" : "arLaercioRedondo",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -53.7386712279912,
        "y" : 461.5782370064508
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690189",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Rego Macedo, Ronaldo do (1950-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690189,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1950,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Rego Macedo, Ronaldo do (1950-)",
        "personId" : "arRonaldoMacedo",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -135.86692920711022,
        "y" : -230.22828308595234
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690186",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 2,
        "shared_name" : "Guimaraens, Luiz Alphonsus de (1948-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690186,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.5,
        "selected" : false,
        "ClosenessCentrality" : 0.6666666666666666,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belo Horizonte",
        "Radiality" : 0.75,
        "birthDate" : 1948,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Guimaraens, Luiz Alphonsus de (1948-)",
        "personId" : "arLuizGuimaraens",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 2.0
      },
      "position" : {
        "x" : 680.3792992662992,
        "y" : -482.07797546102563
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690183",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Paulino, Rosana (1967-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690183,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Paulo",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1967,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Paulino, Rosana (1967-)",
        "personId" : "arRosanaPaulino",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -359.8756581734383,
        "y" : 377.7485107523029
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690180",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Garcia, Zé Carlos (1973-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690180,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Aracaju",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1973,
        "Stress" : 0,
        "birthRegion" : "SE",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Garcia, Zé Carlos (1973-)",
        "personId" : "arZeGarcia",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 144.4776444270408,
        "y" : 17.258936210709994
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690177",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Zerbini, Luiz (1959-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690177,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Paulo",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1959,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Zerbini, Luiz (1959-)",
        "personId" : "arLuizZerbini",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 53.57338609322166,
        "y" : -398.2978914199911
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690174",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual; Diretor(a) de Filme; Escritor(a)",
        "Eccentricity" : 4,
        "shared_name" : "Akerman, Chantal (1950-2015)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Bélgica",
        "SUID" : 2690174,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Bruxelas",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1950,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Akerman, Chantal (1950-2015)",
        "personId" : "arChantalAkerman",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -178.65396346468657,
        "y" : 376.65857282423195
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690171",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Sant’Ana, Tiago (1990-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690171,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Santo Antônio de Jesus",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1990,
        "Stress" : 0,
        "birthRegion" : "BA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Sant’Ana, Tiago (1990-)",
        "personId" : "arTiagoSantAna",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 230.59699813153242,
        "y" : -339.16913201330976
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690168",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Bulcão, Athos (1918-2008)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690168,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1918,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Bulcão, Athos (1918-2008)",
        "personId" : "arAthosBulcao",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -13.095643157350125,
        "y" : -100.8523238842687
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690165",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Silva Costa, Amélia (1976-1922)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690165,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1976,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Silva Costa, Amélia (1976-1922)",
        "personId" : "arAmeliaCosta",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -144.40822428916601,
        "y" : 462.31300081772224
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690162",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Faro, Magdalena del",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Brasil",
        "SUID" : 2690162,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9256661991584852,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Faro, Magdalena del",
        "personId" : "arMagdalenaFaro",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -177.66128516233633,
        "y" : 548.3268783563445
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690159",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Nepomuceno, Maria (1976-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690159,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1976,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Nepomuceno, Maria (1976-)",
        "personId" : "arMariaNepomuceno",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -161.6076128141269,
        "y" : 644.111911998516
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690156",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Martins, Maria (1894-1973)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690156,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Campanha",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1894,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Martins, Maria (1894-1973)",
        "personId" : "arMariaMartins",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -374.0017145826608,
        "y" : 645.2761597272079
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690153",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Salgado, Cristina (1957-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690153,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1957,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Salgado, Cristina (1957-)",
        "personId" : "arCristinaSalgado",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -483.96781733935484,
        "y" : 464.21237556745865
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690150",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Bourgeois, Louise Joséphine (1911-2010)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "França",
        "SUID" : 2690150,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Paris",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1911,
        "Stress" : 0,
        "birthRegion" : "Île de France",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Bourgeois, Louise Joséphine (1911-2010)",
        "personId" : "arLouiseBourgeois",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -376.13032272341286,
        "y" : 282.04604644198247
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690147",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Sá, Neide Dias de (1940-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690147,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1940,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Sá, Neide Dias de (1940-)",
        "personId" : "arNeideSa",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -163.6705657689805,
        "y" : 280.6880030719288
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690144",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Schendel, Mira (1919-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Suíça",
        "SUID" : 2690144,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Zurique",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1919,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Schendel, Mira (1919-1988)",
        "personId" : "arMiraSchendel",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -268.1225160649224,
        "y" : 587.5993937276598
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690141",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Milhazes, Beatriz (1960-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690141,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1960,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Milhazes, Beatriz (1960-)",
        "personId" : "arBeatrizMilhazes",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -358.9858105791496,
        "y" : 549.3039862623389
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690138",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Baltar, Brígida (1959-2022)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690138,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1959,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Baltar, Brígida (1959-2022)",
        "personId" : "arBrigidaBaltar",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -393.25611898183877,
        "y" : 463.6864127024141
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690135",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Houayek, Hugo (1979-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690135,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 3.3043478260869565,
        "selected" : false,
        "ClosenessCentrality" : 0.3026315789473684,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9256661991584852,
        "birthDate" : 1979,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Houayek, Hugo (1979-)",
        "personId" : "arHugoHouayek",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 15.0
      },
      "position" : {
        "x" : -269.5026289091958,
        "y" : 338.3869035341574
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690132",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Basquiat, Jean-Michel (1960-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Estados Unidos",
        "SUID" : 2690132,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Nova Iorque",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1960,
        "Stress" : 0,
        "birthRegion" : "Nova Iorque",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Basquiat, Jean-Michel (1960-1988)",
        "personId" : "arJeanMichelBasquiat",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 276.79208227307697,
        "y" : -269.2828959008301
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690129",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Rocha Pitta, Matheus (1980-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690129,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São João del Rei",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1980,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Rocha Pitta, Matheus (1980-)",
        "personId" : "arMatheusPitta",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 276.4884528691663,
        "y" : -103.20906519899262
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690126",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Freitas, Ana",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690126,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9481065918653576,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Freitas, Ana",
        "personId" : "arAnaFreitas",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 53.71273088618352,
        "y" : 25.74877029733892
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690123",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Lima Dias, Antônio Manuel (1944-2018)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690123,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Campina Grande",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1944,
        "Stress" : 0,
        "birthRegion" : "PB",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Lima Dias, Antônio Manuel (1944-2018)",
        "personId" : "arAntonioDias",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -44.241516992303325,
        "y" : -186.2059421222724
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690120",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Braga, Rodrigo (1976-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690120,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Manaus",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1976,
        "Stress" : 0,
        "birthRegion" : "AM",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Braga, Rodrigo (1976-)",
        "personId" : "arRodrigoBraga",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 77.40571340095681,
        "y" : -312.44650921766475
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690117",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Mello Mourão, Antonio José de (1952-2016)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690117,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Palmares",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1952,
        "Stress" : 0,
        "birthRegion" : "PE",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Mello Mourão, Antonio José de (1952-2016)",
        "personId" : "arAtonioMourao",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -13.133246580348718,
        "y" : -271.57277008663624
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690114",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Freitas, Iole de (1945-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690114,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belo Horizonte",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1945,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Freitas, Iole de (1945-)",
        "personId" : "arIoleFreitas",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 203.1377086250679,
        "y" : -186.33830071640517
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690111",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Fernández, Magdalena (1964-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Venezuela",
        "SUID" : 2690111,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1964,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Fernández, Magdalena (1964-)",
        "personId" : "arMagdalenaFernandez",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 266.0492622649001,
        "y" : 46.864913090405096
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690108",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Vardenega, Gregorio (1923-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Itália",
        "SUID" : 2690108,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1923,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Vardenega, Gregorio (1923-)",
        "personId" : "arGregorioVardenega",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -201.59144064644593,
        "y" : -57.663454789362405
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690105",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Parc, Julio Le (1928-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Argentina",
        "SUID" : 2690105,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Mendoza",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1928,
        "Stress" : 0,
        "birthRegion" : "Mendoza",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Parc, Julio Le (1928-)",
        "personId" : "arJulioParc",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 5.253273549002082,
        "y" : -474.5576427793681
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690102",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Castro, Willys de (1926-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690102,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Uberlândia",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1926,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Castro, Willys de (1926-1988)",
        "personId" : "arWillysCastro",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -36.87775317714205,
        "y" : -7.1319196159746845
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690099",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Serpa, Ivan (1923-1973)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690099,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1923,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Serpa, Ivan (1923-1973)",
        "personId" : "arIvanSerpa",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -104.08615637944912,
        "y" : -61.37502485688225
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690096",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Volpi, Alfredo (1896-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Itália",
        "SUID" : 2690096,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Lucca",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1896,
        "Stress" : 0,
        "birthRegion" : "Toscana",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Volpi, Alfredo (1896-1988)",
        "personId" : "arAlfredoVolpi",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -135.86384684966032,
        "y" : -142.19066051993966
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690093",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Cordeiro, Waldemar (1925-1973)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Itália",
        "SUID" : 2690093,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Roma",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1925,
        "Stress" : 0,
        "birthRegion" : "Lácio",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Cordeiro, Waldemar (1925-1973)",
        "personId" : "arWaldemarCordeiro",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -104.17690223350495,
        "y" : -311.02592305920024
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690090",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 2,
        "shared_name" : "Maiolino, Anna Maria (1942-)",
        "TopologicalCoefficient" : 0.5,
        "idnoEIC" : "EIC",
        "birthCountry" : "Itália",
        "SUID" : 2690090,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.9565217391304348,
        "selected" : false,
        "ClosenessCentrality" : 0.5111111111111111,
        "Degree" : 2,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Scalea",
        "Radiality" : 0.9691444600280505,
        "birthDate" : 1942,
        "Stress" : 930,
        "birthRegion" : "Calábria",
        "BetweennessCentrality" : 0.4492753623188406,
        "NumberOfUndirectedEdges" : 2,
        "name" : "Maiolino, Anna Maria (1942-)",
        "personId" : "arAnnaMaiolino",
        "countTexts" : 2,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 23.0
      },
      "position" : {
        "x" : -116.79739277696304,
        "y" : 183.87081933715908
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690087",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Pape, Lygia (1927-2004)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690087,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Nova Friburgo",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1927,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Pape, Lygia (1927-2004)",
        "personId" : "arLygiaPape",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -36.914725618447314,
        "y" : -365.2008184886971
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690084",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Espírito Santo, Iran do (1963-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690084,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Mococa",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1963,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Espírito Santo, Iran do (1963-)",
        "personId" : "arIranSanto",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 144.26222427593706,
        "y" : -389.79746502778016
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690081",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Pérez Monzón, Gustavo (1956-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Cuba",
        "SUID" : 2690081,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1956,
        "Stress" : 0,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Pérez Monzón, Gustavo (1956-)",
        "personId" : "arGustavoMonzon",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 294.7480155115275,
        "y" : -186.21968682712267
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690078",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Mello, Vicente de (1967-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690078,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "São Paulo",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1967,
        "Stress" : 0,
        "birthRegion" : "SP",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Mello, Vicente de (1967-)",
        "personId" : "arVicenteMello",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 169.30030735885416,
        "y" : -274.8768797611211
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690075",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Machado, Ivens (1942-2015)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690075,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Florianópolis",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1942,
        "Stress" : 0,
        "birthRegion" : "SC",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Machado, Ivens (1942-2015)",
        "personId" : "arIvensMachado",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 169.16746972907487,
        "y" : -97.79693319184354
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690072",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual; Curador(a)",
        "Eccentricity" : 4,
        "shared_name" : "Heráclito, Ayrson (1969-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690072,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Macaúbas",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1969,
        "Stress" : 0,
        "birthRegion" : "BA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Heráclito, Ayrson (1969-)",
        "personId" : "arAyrsonHeraclito",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 5.8331825772381345,
        "y" : 102.3115695791618
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690069",
        "idnoWKD" : "NA",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Magno, Luciana (1987-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690069,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belém",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1987,
        "Stress" : 0,
        "birthRegion" : "PA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Magno, Luciana (1987-)",
        "personId" : "arLucianaMagno",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : -201.72489842100808,
        "y" : -314.6249200289457
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690066",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Reale, Berna (1965-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690066,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belém",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1965,
        "Stress" : 0,
        "birthRegion" : "PA",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Reale, Berna (1965-)",
        "personId" : "arBernaReale",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 265.25256276064556,
        "y" : -420.00411148199345
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690063",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Clark, Lygia (1920-1988)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690063,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Belo Horizonte",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1920,
        "Stress" : 0,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Clark, Lygia (1920-1988)",
        "personId" : "arLygiaClark",
        "countTexts" : 1,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 230.34561032556638,
        "y" : -33.4345469070863
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690060",
        "idnoWKD" : "WKD",
        "occupation" : "Artista Visual",
        "Eccentricity" : 4,
        "shared_name" : "Oiticica, Hélio (1937-1980)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "EIC",
        "birthCountry" : "Brasil",
        "SUID" : 2690060,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.608695652173913,
        "selected" : false,
        "ClosenessCentrality" : 0.3833333333333333,
        "Degree" : 1,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 0.9481065918653576,
        "birthDate" : 1937,
        "Stress" : 0,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 0.0,
        "NumberOfUndirectedEdges" : 1,
        "name" : "Oiticica, Hélio (1937-1980)",
        "personId" : "arHelioOiticica",
        "countTexts" : 2,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 31.0
      },
      "position" : {
        "x" : 77.44055412281882,
        "y" : -60.05890440519862
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690057",
        "idnoWKD" : "NA",
        "occupation" : "Historiador(a) da Arte",
        "Eccentricity" : 1,
        "shared_name" : "Lattavo, Patricia (1968-)",
        "TopologicalCoefficient" : 0.0,
        "idnoEIC" : "NA",
        "birthCountry" : "Brasil",
        "SUID" : 2690057,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.0,
        "selected" : false,
        "ClosenessCentrality" : 1.0,
        "Degree" : 2,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "Rio de Janeiro",
        "Radiality" : 1.0,
        "birthDate" : 1968,
        "Stress" : 2,
        "birthRegion" : "RJ",
        "BetweennessCentrality" : 1.0,
        "NumberOfUndirectedEdges" : 2,
        "name" : "Lattavo, Patricia (1968-)",
        "personId" : "auPatriciaLattavo",
        "countTexts" : 2,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 1.0
      },
      "position" : {
        "x" : 589.6058352422848,
        "y" : -452.67476814630265
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690051",
        "idnoWKD" : "NA",
        "occupation" : "Curador(a)",
        "Eccentricity" : 3,
        "shared_name" : "Fonseca, Ludimilla (1989-)",
        "TopologicalCoefficient" : 0.06666666666666667,
        "idnoEIC" : "NA",
        "birthCountry" : "Brasil",
        "SUID" : 2690051,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 2.3260869565217392,
        "selected" : false,
        "ClosenessCentrality" : 0.42990654205607476,
        "Degree" : 15,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.9572230014025246,
        "birthDate" : 1989,
        "Stress" : 1078,
        "birthRegion" : "MG",
        "BetweennessCentrality" : 0.5207729468599034,
        "NumberOfUndirectedEdges" : 15,
        "name" : "Fonseca, Ludimilla (1989-)",
        "personId" : "auLudmillaFonseca",
        "countTexts" : 5,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 1.0666666666666667
      },
      "position" : {
        "x" : -268.79025895844404,
        "y" : 463.01310940689433
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690024",
        "idnoWKD" : "NA",
        "occupation" : "Historiador(a) da Arte; Artista Visual",
        "Eccentricity" : 3,
        "shared_name" : "Veiga, Valesca",
        "TopologicalCoefficient" : 0.03225806451612903,
        "idnoEIC" : "NA",
        "birthCountry" : "Brasil",
        "SUID" : 2690024,
        "SelfLoops" : 0,
        "NumberOfDirectedEdges" : 0,
        "AverageShortestPathLength" : 1.6304347826086956,
        "selected" : false,
        "ClosenessCentrality" : 0.6133333333333334,
        "Degree" : 31,
        "PartnerOfMultiEdgedNodePairs" : 0,
        "ClusteringCoefficient" : 0.0,
        "birthCity" : "NA",
        "Radiality" : 0.979663394109397,
        "Stress" : 1830,
        "birthRegion" : "NA",
        "BetweennessCentrality" : 0.8840579710144927,
        "NumberOfUndirectedEdges" : 31,
        "name" : "Veiga, Valesca",
        "personId" : "auValescaVeiga",
        "countTexts" : 16,
        "IsSingleNode" : false,
        "NeighborhoodConnectivity" : 1.032258064516129
      },
      "position" : {
        "x" : 79.44441205719961,
        "y" : -186.28763339559617
      },
      "selected" : false
    } ],
    "edges" : [ {
      "data" : {
        "id" : "2690295",
        "source" : "2690057",
        "target" : "2690198",
        "EdgeBetweenness" : 4.0,
        "shared_name" : "auPatriciaLattavo (-) arFredericoFilippi",
        "shared_interaction" : "-",
        "name" : "auPatriciaLattavo (-) arFredericoFilippi",
        "interaction" : "-",
        "SUID" : 2690295,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690289",
        "source" : "2690057",
        "target" : "2690186",
        "EdgeBetweenness" : 4.0,
        "shared_name" : "auPatriciaLattavo (-) arLuizGuimaraens",
        "shared_interaction" : "-",
        "name" : "auPatriciaLattavo (-) arLuizGuimaraens",
        "interaction" : "-",
        "SUID" : 2690289,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690293",
        "source" : "2690051",
        "target" : "2690192",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arLaercioRedondo",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arLaercioRedondo",
        "interaction" : "-",
        "SUID" : 2690293,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690287",
        "source" : "2690051",
        "target" : "2690183",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arRosanaPaulino",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arRosanaPaulino",
        "interaction" : "-",
        "SUID" : 2690287,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690281",
        "source" : "2690051",
        "target" : "2690174",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arChantalAkerman",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arChantalAkerman",
        "interaction" : "-",
        "SUID" : 2690281,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690275",
        "source" : "2690051",
        "target" : "2690165",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arAmeliaCosta",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arAmeliaCosta",
        "interaction" : "-",
        "SUID" : 2690275,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690273",
        "source" : "2690051",
        "target" : "2690162",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arMagdalenaFaro",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arMagdalenaFaro",
        "interaction" : "-",
        "SUID" : 2690273,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690271",
        "source" : "2690051",
        "target" : "2690159",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arMariaNepomuceno",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arMariaNepomuceno",
        "interaction" : "-",
        "SUID" : 2690271,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690269",
        "source" : "2690051",
        "target" : "2690156",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arMariaMartins",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arMariaMartins",
        "interaction" : "-",
        "SUID" : 2690269,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690267",
        "source" : "2690051",
        "target" : "2690153",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arCristinaSalgado",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arCristinaSalgado",
        "interaction" : "-",
        "SUID" : 2690267,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690265",
        "source" : "2690051",
        "target" : "2690150",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arLouiseBourgeois",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arLouiseBourgeois",
        "interaction" : "-",
        "SUID" : 2690265,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690263",
        "source" : "2690051",
        "target" : "2690147",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arNeideSa",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arNeideSa",
        "interaction" : "-",
        "SUID" : 2690263,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690261",
        "source" : "2690051",
        "target" : "2690144",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arMiraSchendel",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arMiraSchendel",
        "interaction" : "-",
        "SUID" : 2690261,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690259",
        "source" : "2690051",
        "target" : "2690141",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arBeatrizMilhazes",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arBeatrizMilhazes",
        "interaction" : "-",
        "SUID" : 2690259,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690257",
        "source" : "2690051",
        "target" : "2690138",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arBrigidaBaltar",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arBrigidaBaltar",
        "interaction" : "-",
        "SUID" : 2690257,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690255",
        "source" : "2690051",
        "target" : "2690090",
        "EdgeBetweenness" : 960.0,
        "shared_name" : "auLudmillaFonseca (-) arAnnaMaiolino",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arAnnaMaiolino",
        "interaction" : "-",
        "SUID" : 2690255,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690253",
        "source" : "2690051",
        "target" : "2690135",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auLudmillaFonseca (-) arHugoHouayek",
        "shared_interaction" : "-",
        "name" : "auLudmillaFonseca (-) arHugoHouayek",
        "interaction" : "-",
        "SUID" : 2690253,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690297",
        "source" : "2690024",
        "target" : "2690195",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arJanainaLandini",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arJanainaLandini",
        "interaction" : "-",
        "SUID" : 2690297,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690291",
        "source" : "2690024",
        "target" : "2690189",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arRonaldoMacedo",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arRonaldoMacedo",
        "interaction" : "-",
        "SUID" : 2690291,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690285",
        "source" : "2690024",
        "target" : "2690177",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arLuizZerbini",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arLuizZerbini",
        "interaction" : "-",
        "SUID" : 2690285,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690283",
        "source" : "2690024",
        "target" : "2690171",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arTiagoSantAna",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arTiagoSantAna",
        "interaction" : "-",
        "SUID" : 2690283,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690279",
        "source" : "2690024",
        "target" : "2690180",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arZeGarcia",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arZeGarcia",
        "interaction" : "-",
        "SUID" : 2690279,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690277",
        "source" : "2690024",
        "target" : "2690168",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAthosBulcao",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAthosBulcao",
        "interaction" : "-",
        "SUID" : 2690277,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690251",
        "source" : "2690024",
        "target" : "2690132",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arJeanMichelBasquiat",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arJeanMichelBasquiat",
        "interaction" : "-",
        "SUID" : 2690251,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690249",
        "source" : "2690024",
        "target" : "2690129",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arMatheusPitta",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arMatheusPitta",
        "interaction" : "-",
        "SUID" : 2690249,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690247",
        "source" : "2690024",
        "target" : "2690126",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAnaFreitas",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAnaFreitas",
        "interaction" : "-",
        "SUID" : 2690247,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690245",
        "source" : "2690024",
        "target" : "2690123",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAntonioDias",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAntonioDias",
        "interaction" : "-",
        "SUID" : 2690245,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690243",
        "source" : "2690024",
        "target" : "2690120",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arRodrigoBraga",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arRodrigoBraga",
        "interaction" : "-",
        "SUID" : 2690243,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690241",
        "source" : "2690024",
        "target" : "2690114",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arIoleFreitas",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arIoleFreitas",
        "interaction" : "-",
        "SUID" : 2690241,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690239",
        "source" : "2690024",
        "target" : "2690111",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arMagdalenaFernandez",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arMagdalenaFernandez",
        "interaction" : "-",
        "SUID" : 2690239,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690237",
        "source" : "2690024",
        "target" : "2690108",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arGregorioVardenega",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arGregorioVardenega",
        "interaction" : "-",
        "SUID" : 2690237,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690235",
        "source" : "2690024",
        "target" : "2690105",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arJulioParc",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arJulioParc",
        "interaction" : "-",
        "SUID" : 2690235,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690233",
        "source" : "2690024",
        "target" : "2690102",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arWillysCastro",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arWillysCastro",
        "interaction" : "-",
        "SUID" : 2690233,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690231",
        "source" : "2690024",
        "target" : "2690099",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arIvanSerpa",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arIvanSerpa",
        "interaction" : "-",
        "SUID" : 2690231,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690229",
        "source" : "2690024",
        "target" : "2690096",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAlfredoVolpi",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAlfredoVolpi",
        "interaction" : "-",
        "SUID" : 2690229,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690227",
        "source" : "2690024",
        "target" : "2690093",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arWaldemarCordeiro",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arWaldemarCordeiro",
        "interaction" : "-",
        "SUID" : 2690227,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690225",
        "source" : "2690024",
        "target" : "2690090",
        "EdgeBetweenness" : 992.0,
        "shared_name" : "auValescaVeiga (-) arAnnaMaiolino",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAnnaMaiolino",
        "interaction" : "-",
        "SUID" : 2690225,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690223",
        "source" : "2690024",
        "target" : "2690087",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arLygiaPape",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arLygiaPape",
        "interaction" : "-",
        "SUID" : 2690223,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690221",
        "source" : "2690024",
        "target" : "2690084",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arIranSanto",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arIranSanto",
        "interaction" : "-",
        "SUID" : 2690221,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690219",
        "source" : "2690024",
        "target" : "2690081",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arGustavoMonzon",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arGustavoMonzon",
        "interaction" : "-",
        "SUID" : 2690219,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690217",
        "source" : "2690024",
        "target" : "2690063",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arLygiaClark",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arLygiaClark",
        "interaction" : "-",
        "SUID" : 2690217,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690215",
        "source" : "2690024",
        "target" : "2690060",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arHelioOiticica",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arHelioOiticica",
        "interaction" : "-",
        "SUID" : 2690215,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 2
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690213",
        "source" : "2690024",
        "target" : "2690117",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAtonioMourao",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAtonioMourao",
        "interaction" : "-",
        "SUID" : 2690213,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690211",
        "source" : "2690024",
        "target" : "2690078",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arVicenteMello",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arVicenteMello",
        "interaction" : "-",
        "SUID" : 2690211,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690209",
        "source" : "2690024",
        "target" : "2690075",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arIvensMachado",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arIvensMachado",
        "interaction" : "-",
        "SUID" : 2690209,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690207",
        "source" : "2690024",
        "target" : "2690072",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arAyrsonHeraclito",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arAyrsonHeraclito",
        "interaction" : "-",
        "SUID" : 2690207,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690205",
        "source" : "2690024",
        "target" : "2690069",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arLucianaMagno",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arLucianaMagno",
        "interaction" : "-",
        "SUID" : 2690205,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "2690203",
        "source" : "2690024",
        "target" : "2690066",
        "EdgeBetweenness" : 92.0,
        "shared_name" : "auValescaVeiga (-) arBernaReale",
        "shared_interaction" : "-",
        "name" : "auValescaVeiga (-) arBernaReale",
        "interaction" : "-",
        "SUID" : 2690203,
        "selected" : false,
        "NumberOfUnderlyingEdges" : 1
      },
      "selected" : false
    } ]
  }
}}